app = 'ibm-project-broken-wind-6280'
primary_region = 'syd'

[build]

[processes]
  app = "/app/.venv/bin/python app.py"
  worker = "/app/.venv/bin/python worker.py"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']  # Only the app process serves HTTP

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ["app"]  # This VM runs the app

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ["worker"]  # This VM runs the worker